### ISSUE TITLE
Add suggested PoC

### ISSUE THREAD

**Issue by moneyball** [ajtowns/taproot-review#28]
<img width="998" alt="Screen Shot 2019-11-06 at 2 22 56 PM" src="https://user-images.githubusercontent.com/326147/68343136-00b7c680-00a1-11ea-9310-21e56047469a.png">

**Comment by jachiang** [comment]
Just to add some context: The conversation started around Pieter's gated CSA tapscript idea, which, as we discovered, requires witnesses of a smaller stack size than straight-up k-of-n CSAs. Such a setup features CSA with gated null's for each PK, and requires a witness stack size of ~k rather than n. A regular CSA requires a spending witness stack size of n elements.

Why is this useful: For large n, the script stack limit of 1000 is a constraint for regular CSA's, but not for this gated CSA setup. A gated CSA works around this limit (witstack size of ~k rather than n), at the cost of a higher spending transaction weight. The proposal by AJ (which is shown above) isn't specific to taproot/tapscript/CSA, but achieves the same principle with checksigverify, albeit with more op-codes. 

A PoC script for a gated CSA setup would be interesting. Though I am unsure of the practicality of >1000 PK CSA.
